import type { ChapterContent } from "@/content/types";

/**
 * Trigonometry — T06 production content.
 *
 * Evidence discipline:
 * - No weightage, trend or PYQ-count claims.
 * - No named contributor; author/reviewer remain unassigned pending review.
 * - contentStatus stays "draft" until academic review is recorded.
 * - Main 2026 Unit 14 covers trigonometric identities and functions; Unit 7
 *   separately covers trigonometric functions among real-valued functions.
 *   Main wording does not separately enumerate general solutions, addition
 *   or multiple-angle formulae as standalone Unit 14 bullets. Advanced 2026
 *   explicitly includes periodicity, graphs, addition/subtraction formulae,
 *   multiple/sub-multiple angle formulae and general solutions.
 */
export const jeeMathematicsTrigonometry: ChapterContent = {
  exam: "JEE",
  platform: "jee",
  subject: "Mathematics",
  subjectSlug: "mathematics",
  chapter: "Trigonometry",
  slug: "trigonometry",
  url: "/jee/mathematics/trigonometry",
  canonicalIntent:
    "Build the ordinary trigonometric system, recognise function domains and periodicity, select identities or equations correctly, and transform expressions without illegal division by a trigonometric expression that may be zero.",

  heroChips: [
    "Main 2026 Unit 14: trigonometric identities and functions",
    "Advanced 2026: explicit general solutions, addition and multiple-angle formulae",
    "No invented weightage, question counts or trend percentages",
  ],

  directAnswer: [
    {
      type: "paragraph",
      children: [
        {
          text: "Trigonometry studies periodic functions generated by angles and the unit circle. Strong solving begins by identifying which trigonometric functions are defined, choosing an identity that preserves the solution set, and validating every value against the original equation.",
        },
      ],
    },
    {
      type: "note",
      tone: "caution",
      children: [
        {
          text: "Never divide by sin x, cos x, tan x or another trigonometric expression unless the zero case has first been handled.",
        },
      ],
    },
    {
      type: "note",
      tone: "info",
      children: [
        {
          text: "JEE Main 2026 Unit 14 explicitly includes trigonometric identities and trigonometric functions; Unit 7 separately includes trigonometric functions among real-valued functions and simple-function graphs. The Main wording does not separately enumerate general solutions of trigonometric equations, addition/subtraction formulae, or multiple/sub-multiple angle formulae as standalone Unit 14 bullets.",
        },
      ],
    },
    {
      type: "note",
      tone: "info",
      children: [
        {
          text: "JEE Advanced 2026 explicitly includes trigonometric functions, periodicity and graphs, addition and subtraction formulae, multiple and sub-multiple angle formulae, and general solutions of trigonometric equations.",
        },
      ],
    },
  ],

  prerequisites: [
    {
      label: "Functions",
      url: "/jee/mathematics/functions",
      relation: "prerequisite",
      description: "Function domains and graphs underlie recognising where each trigonometric function is defined.",
    },
    {
      label: "JEE Mathematics",
      url: "/jee/mathematics",
      relation: "up",
      description: "Subject hub for the Mathematics chapter set.",
    },
  ],

  syllabusMapping: {
    unit: "Trigonometry",
    topics: [
      "Trigonometric functions and identities",
      "Periodicity and graphs",
      "Addition and subtraction formulae",
      "Multiple and sub-multiple angle formulae",
      "General solutions of trigonometric equations",
    ],
    syllabusUrl: "/jee/syllabus/mathematics",
  },

  conceptBlocks: [
    {
      id: "angle-representation",
      title: "1. Put angles in one unit before calculation",
      keyIdea: "Convert degree and radian values consistently before any calculus or identity work.",
      body: [
        {
          type: "paragraph",
          children: [
            {
              text: "Degree and radian conversion is foundational supporting mathematics. The 2026 Main Unit 14 and Advanced Trigonometry wording do not separately list angle measure as a named syllabus bullet; teach it as prerequisite language, not a fabricated explicit bullet.",
            },
          ],
        },
      ],
    },
    {
      id: "domain-check",
      title: "2. Record where each expression is defined",
      keyIdea: "tan x and sec x require cos x≠0; cot x and csc x require sin x≠0.",
      body: [
        {
          type: "paragraph",
          children: [
            { text: "Before simplifying or solving, record the domain restriction attached to every trigonometric expression in the problem." },
          ],
        },
      ],
    },
    {
      id: "identity-model",
      title: "3. Prefer identities that reduce the number of different trigonometric functions",
      keyIdea: "Fewer distinct function families make factoring and solving safer.",
      body: [
        {
          type: "paragraph",
          children: [{ text: "Convert compound expressions toward one function family before factoring or equating." }],
        },
      ],
    },
    {
      id: "zero-case-protection",
      title: "4. Solve factors separately, never divide by one factor",
      keyIdea: "If factoring gives a product, solve each factor rather than dividing by one factor.",
      body: [
        {
          type: "paragraph",
          children: [{ text: "Dividing a trigonometric equation by sin x or cos x silently discards the branch where that factor is zero." }],
        },
      ],
    },
    {
      id: "solve-interval-or-general",
      title: "5. Account for periodicity or the requested interval",
      keyIdea: "A specific interval keeps only the solutions inside it; a general solution needs the full periodic family.",
      body: [
        {
          type: "paragraph",
          children: [{ text: "Advanced-explicit general solution families for sine, cosine and tangent equations should not be presented as separately named Main Unit 14 bullets." }],
        },
      ],
    },
    {
      id: "substitute-back",
      title: "6. Substitute solutions into the original equation",
      keyIdea: "Validation catches extraneous roots introduced by squaring or denominator manipulation.",
      body: [
        {
          type: "paragraph",
          children: [{ text: "Every candidate solution should be substituted back into the original equation, especially after squaring or clearing a denominator." }],
        },
      ],
    },
  ],

  formulas: [
    {
      id: "degree-radian",
      expression: "180°=π rad",
      meaning: "Degree-radian conversion",
      variables: [],
      useWhen: "Converting angle units",
      commonTrap: "Mixing degree values with radian calculus formulas",
      accessibleText: "180 degrees equals pi radians",
    },
    {
      id: "pythagorean-identity",
      expression: "sin²x+cos²x=1",
      meaning: "Pythagorean identity",
      variables: [{ symbol: "x", meaning: "any real angle" }],
      useWhen: "Reducing squares",
      commonTrap: "Dividing by sin or cos without a zero check",
      accessibleText: "sine squared x plus cosine squared x equals 1, valid for all real x",
    },
    {
      id: "tan-definition",
      expression: "tan x=sin x/cos x",
      meaning: "Tangent definition",
      variables: [{ symbol: "x", meaning: "angle where cos x≠0" }],
      useWhen: "Converting to sin/cos",
      commonTrap: "Forgetting excluded points where cos x=0",
      accessibleText: "tangent x equals sine x over cosine x, defined only when cosine x is not zero",
    },
    {
      id: "cot-definition",
      expression: "cot x=cos x/sin x",
      meaning: "Cotangent definition",
      variables: [{ symbol: "x", meaning: "angle where sin x≠0" }],
      useWhen: "Converting to sin/cos",
      commonTrap: "Forgetting excluded points where sin x=0",
      accessibleText: "cotangent x equals cosine x over sine x, defined only when sine x is not zero",
    },
    {
      id: "sec-identity",
      expression: "1+tan²x=sec²x",
      meaning: "Secant identity",
      variables: [{ symbol: "x", meaning: "angle where cos x≠0" }],
      useWhen: "Expressions in tan/sec",
      commonTrap: "Treating it as valid at cos x=0",
      accessibleText: "1 plus tangent squared x equals secant squared x, valid where cosine x is not zero",
    },
    {
      id: "csc-identity",
      expression: "1+cot²x=csc²x",
      meaning: "Cosecant identity",
      variables: [{ symbol: "x", meaning: "angle where sin x≠0" }],
      useWhen: "Expressions in cot/csc",
      commonTrap: "Treating it as valid at sin x=0",
      accessibleText: "1 plus cotangent squared x equals cosecant squared x, valid where sine x is not zero",
    },
    {
      id: "addition-sine",
      expression: "sin(A+B)=sinA cosB+cosA sinB",
      meaning: "Addition formula",
      variables: [{ symbol: "A", meaning: "real angle" }, { symbol: "B", meaning: "real angle" }],
      useWhen: "Compound angles",
      commonTrap: "Sign error",
      accessibleText: "sine of A plus B equals sine A cosine B plus cosine A sine B",
    },
    {
      id: "subtraction-sine",
      expression: "sin(A-B)=sinA cosB-cosA sinB",
      meaning: "Subtraction formula",
      variables: [{ symbol: "A", meaning: "real angle" }, { symbol: "B", meaning: "real angle" }],
      useWhen: "Compound angles",
      commonTrap: "Sign error",
      accessibleText: "sine of A minus B equals sine A cosine B minus cosine A sine B",
    },
    {
      id: "addition-cosine",
      expression: "cos(A+B)=cosA cosB-sinA sinB",
      meaning: "Cosine addition",
      variables: [{ symbol: "A", meaning: "real angle" }, { symbol: "B", meaning: "real angle" }],
      useWhen: "Compound angles",
      commonTrap: "Wrong middle sign",
      accessibleText: "cosine of A plus B equals cosine A cosine B minus sine A sine B",
    },
    {
      id: "addition-tangent",
      expression: "tan(A+B)=(tanA+tanB)/(1-tanA tanB)",
      meaning: "Tangent addition",
      variables: [{ symbol: "A", meaning: "angle with tan A defined" }, { symbol: "B", meaning: "angle with tan B defined" }],
      useWhen: "Compound tangent",
      commonTrap: "Blind cross-multiplication at excluded points; tan A, tan B and tan(A+B) must all be defined and the displayed denominator nonzero",
      accessibleText: "tangent of A plus B equals tangent A plus tangent B over 1 minus tangent A tangent B",
    },
    {
      id: "double-angle-sine",
      expression: "sin2x=2sinx cosx",
      meaning: "Double-angle sine",
      variables: [{ symbol: "x", meaning: "any real angle" }],
      useWhen: "Product/angle reduction",
      commonTrap: "Dividing by sin or cos",
      accessibleText: "sine of 2x equals 2 sine x cosine x",
    },
    {
      id: "double-angle-cosine",
      expression: "cos2x=cos²x-sin²x=1-2sin²x=2cos²x-1",
      meaning: "Double-angle cosine",
      variables: [{ symbol: "x", meaning: "any real angle" }],
      useWhen: "Quadratic trig forms",
      commonTrap: "Selecting the wrong rearrangement",
      accessibleText: "cosine of 2x equals cosine squared x minus sine squared x, equals 1 minus 2 sine squared x, equals 2 cosine squared x minus 1",
    },
    {
      id: "general-sine-solution",
      expression: "sin x=sin α -> x=nπ+(-1)^n α",
      meaning: "Advanced general sine solution",
      variables: [{ symbol: "n", meaning: "integer, n∈Z" }, { symbol: "α", meaning: "a chosen representative angle" }],
      useWhen: "Advanced general solutions",
      commonTrap: "Missing families; the original equation and domain still control",
      accessibleText: "if sine x equals sine alpha then x equals n pi plus negative one to the n times alpha, for integer n",
    },
    {
      id: "general-cosine-solution",
      expression: "cos x=cos α -> x=2nπ±α",
      meaning: "Advanced general cosine solution",
      variables: [{ symbol: "n", meaning: "integer, n∈Z" }],
      useWhen: "Advanced general solutions",
      commonTrap: "Treating the plus-minus as one family",
      accessibleText: "if cosine x equals cosine alpha then x equals 2 n pi plus or minus alpha, for integer n",
    },
    {
      id: "general-tangent-solution",
      expression: "tan x=tan α -> x=nπ+α",
      meaning: "Advanced general tangent solution",
      variables: [{ symbol: "n", meaning: "integer, n∈Z" }],
      useWhen: "Advanced general solutions",
      commonTrap: "Including tangent poles where both sides must be defined",
      accessibleText: "if tangent x equals tangent alpha then x equals n pi plus alpha, for integer n",
    },
  ],

  tables: [
    {
      id: "chapter-snapshot",
      slot: "scope",
      heading: "What this chapter contains and why it matters",
      columns: ["Question", "Direct answer"],
      rows: [
        [
          "What is the chapter about?",
          "Trigonometric function domains, periodicity, identities and equation-solving with zero-denominator safeguards.",
        ],
        [
          "What is the central method choice?",
          "Identify defined domains, prefer identities that reduce function count, factor rather than divide, and validate every candidate against the original equation.",
        ],
        [
          "Where do most mistakes begin?",
          "Dividing by sin x or cos x without a zero check, mixing degrees and radians, and presenting an Advanced-only general solution as Main scope.",
        ],
        [
          "What should come before Trigonometry?",
          "Functions, domains and graphs, algebraic factorisation, angle notation and coordinate-plane basics.",
        ],
        [
          "What comes after it?",
          "Inverse Trigonometry restricts these functions to principal branches; Limits and Continuity and Calculus use trigonometric behaviour further.",
        ],
      ],
      note: "The official JEE documents define content scope. They do not publish chapter weightage, so none is asserted here.",
    },
    {
      id: "official-syllabus",
      jump: true,
      slot: "scope",
      heading: "Official JEE syllabus mapping for Trigonometry",
      columns: ["Concept group", "JEE Main 2026", "JEE Advanced 2026", "Preparation note"],
      rows: [
        [
          "Trigonometric functions and identities",
          "Explicitly listed under Unit 14; also present via Unit 7 real-valued functions.",
          "Explicitly listed, including periodicity and graphs.",
          "Both papers cover functions and identities; treat periodicity and graphs as Advanced-explicit detail.",
        ],
        [
          "Addition, subtraction and multiple-angle formulae",
          "Not separately enumerated as standalone Unit 14 bullets.",
          "Explicitly listed.",
          "Teach these formulas but do not claim a standalone Main bullet for them.",
        ],
        [
          "General solutions of trigonometric equations",
          "Not separately enumerated as a standalone Unit 14 bullet.",
          "Explicitly listed.",
          "Present general-solution families as Advanced-explicit scope.",
        ],
      ],
      note: "Sources: JEE Main 2026 syllabus and JEE Advanced 2026 syllabus, linked in the sources section below.",
    },
    {
      id: "prerequisite-check",
      jump: true,
      slot: "prerequisites",
      heading: "Prerequisites: what you should know before Trigonometry",
      columns: ["Prerequisite", "You are ready if you can…", "If not, repair this first"],
      rows: [
        ["Function domains and graphs", "Identify where a function is defined and read its graph.", "Revise domain and graph basics in Functions."],
        ["Algebraic factorisation", "Factor a quadratic expression in one variable.", "Revise factoring methods before treating trig equations as polynomials in sin or cos."],
        ["Angle notation", "Distinguish degree and radian notation.", "Revise the degree-radian conversion."],
        ["Coordinate-plane basics", "Read coordinates and interpret the unit circle.", "Revise coordinate-plane fundamentals."],
      ],
      note: "This is a readiness check, not a weightage or scoring-priority list.",
    },
    {
      id: "method-selector",
      jump: true,
      slot: "concepts",
      heading: "Method selector: identity simplification versus equation solving",
      intro: "Match the question signal to the correct first model.",
      columns: ["Question signal", "First model", "Required check"],
      rows: [
        ["Identity simplification", "Convert toward one function family", "Preserve denominator restrictions"],
        ["Equation polynomial in sin or cos", "Substitute a single variable, solve algebraically", "Enforce the range [-1,1]"],
        ["Product equals zero", "Solve factors separately", "Do not divide away a zero branch"],
        ["Specific interval", "List only solutions inside the interval", "Check interval endpoints"],
        ["General solution", "Use Advanced-explicit periodic families", "Confirm Advanced scope, not Main"],
        ["Graph/period question", "Establish domain, range, period and transformation", "Sketch only after these are fixed"],
      ],
    },
    {
      id: "object-definitions",
      jump: true,
      slot: "concepts",
      heading: "Mathematical object definitions",
      columns: ["Object", "Definition or role"],
      rows: [
        ["Radian", "Angle subtending an arc equal in length to the radius; π radians equals 180°."],
        ["sin x", "Unit-circle y-coordinate; defined for all real x."],
        ["cos x", "Unit-circle x-coordinate; defined for all real x."],
        ["tan x", "sin x/cos x; defined only when cos x≠0."],
        ["cot x", "cos x/sin x; defined only when sin x≠0."],
        ["sec x", "1/cos x; defined only when cos x≠0."],
        ["csc x", "1/sin x; defined only when sin x≠0."],
        ["Period", "Positive T for which f(x+T)=f(x) throughout the function's domain; the least such positive T, when it exists, is the fundamental period."],
        ["Trigonometric identity", "Equality true for all inputs for which both sides are defined."],
        ["Trigonometric equation", "Equality to be solved only for inputs in the stated domain or interval."],
      ],
    },
  ],

  sections: [
    {
      id: "worked-quadratic-trig",
      slot: "concepts",
      heading: "Worked reasoning: quadratic in sin x",
      jump: true,
      concepts: [
        {
          id: "worked-example",
          title: "Solve 2sin²x-3sinx+1=0 on [0,2π)",
          body: [
            { type: "paragraph", children: [{ text: "Known: the equation is quadratic in sin x. Find: all x in the requested interval." }] },
            { type: "paragraph", children: [{ text: "Method choice: factor in the single trig variable rather than divide by a trigonometric expression: (2sinx-1)(sinx-1)=0. Therefore sinx=1/2 or sinx=1." }] },
            { type: "paragraph", children: [{ text: "On [0,2π): sinx=1/2 gives x=π/6, 5π/6. sinx=1 gives x=π/2." }] },
            { type: "paragraph", children: [{ text: "Answer: x∈{π/6, π/2, 5π/6}. Validity check: substitute each value into the original quadratic; all satisfy it and all lie in the stated interval." }] },
          ],
        },
      ],
    },
  ],

  mistakes: [
    {
      id: "dividing-by-sin-cos",
      mistake: "Dividing by sin x or cos x and losing valid zero solutions.",
      why: [{ type: "paragraph", children: [{ text: "Dividing by a factor that can be zero silently discards the branch where that factor equals zero." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Factor the equation and solve each factor separately instead of dividing." }] }],
      errorType: "decision-error",
    },
    {
      id: "tangent-identity-at-undefined-points",
      mistake: "Applying tangent identities at points where tangent is undefined.",
      why: [{ type: "paragraph", children: [{ text: "tan x requires cos x≠0; identities involving tan or sec inherit this restriction." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Check the domain of every tangent or secant expression before applying an identity." }] }],
      errorType: "execution-error",
    },
    {
      id: "mixing-degrees-radians",
      mistake: "Mixing degrees and radians.",
      why: [{ type: "paragraph", children: [{ text: "Formulas and calculus results assume a single consistent angle unit." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Convert all angles to one unit before calculating." }] }],
      errorType: "execution-error",
    },
    {
      id: "identity-vs-equation",
      mistake: "Treating an equation as an identity.",
      why: [{ type: "paragraph", children: [{ text: "An identity holds for all valid inputs; an equation holds only for specific inputs." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Confirm whether the statement is claimed to hold universally or only for the values being solved for." }] }],
      errorType: "knowledge-gap",
    },
    {
      id: "principal-vs-general-solution",
      mistake: "Giving one principal solution when a general solution is requested.",
      why: [{ type: "paragraph", children: [{ text: "Trigonometric equations are periodic; a single value misses the full solution family." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Use the Advanced-explicit general-solution formula appropriate to the equation." }] }],
      errorType: "decision-error",
    },
    {
      id: "forgetting-interval-endpoints",
      mistake: "Forgetting interval endpoints.",
      why: [{ type: "paragraph", children: [{ text: "Endpoint inclusion or exclusion changes which solutions are valid." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Re-check the stated interval's open or closed endpoints before finalising the answer set." }] }],
      errorType: "execution-error",
    },
    {
      id: "squaring-extraneous",
      mistake: "Squaring an equation and failing to check extraneous solutions.",
      why: [{ type: "paragraph", children: [{ text: "Squaring can introduce solutions that do not satisfy the original equation." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Substitute every candidate back into the original equation before accepting it." }] }],
      errorType: "execution-error",
    },
    {
      id: "advanced-scope-as-main",
      mistake: "Presenting Advanced-explicit equation families as separately named Main Unit 14 bullets.",
      why: [{ type: "paragraph", children: [{ text: "Main 2026 Unit 14 does not separately enumerate general solutions, addition or multiple-angle formulae as standalone bullets." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Check the official-scope mapping table on this page before attributing scope to Main." }] }],
      errorType: "knowledge-gap",
    },
  ],

  relatedChapters: [
    {
      label: "Inverse Trigonometry",
      url: "/jee/mathematics/inverse-trigonometry",
      relation: "same-unit",
      description: "Restricts ordinary trigonometric functions to principal branches for inversion.",
    },
    {
      label: "Limits and Continuity",
      url: "/jee/mathematics/limits-continuity",
      relation: "forward",
      description: "Uses trigonometric limits and continuity of trigonometric functions.",
    },
    {
      label: "Calculus",
      url: "/jee/mathematics/calculus",
      relation: "forward",
      description: "Trigonometric functions appear throughout differentiation, integration and equation contexts.",
    },
    {
      label: "Functions",
      url: "/jee/mathematics/functions",
      relation: "prerequisite",
      description: "Domain, graph and periodicity language required before trigonometric functions.",
    },
  ],

  links: [
    {
      label: "JEE Mathematics Syllabus",
      url: "/jee/syllabus/mathematics",
      relation: "up",
      description: "Official syllabus mapping for the Mathematics chapter set.",
    },
    {
      label: "JEE Mathematics",
      url: "/jee/mathematics",
      relation: "up",
      description: "Subject hub for the Mathematics chapter set.",
    },
  ],

  faqs: [
    {
      question: "When is tan x undefined?",
      answer: [{ type: "paragraph", children: [{ text: "tan x is undefined whenever cos x=0, since tan x=sin x/cos x." }] }],
    },
    {
      question: "Why should you not divide a trigonometric equation by sin x blindly?",
      answer: [{ type: "paragraph", children: [{ text: "Dividing by sin x discards the branch where sin x=0, which may contain valid solutions. Factor instead of dividing." }] }],
    },
    {
      question: "What is the difference between an identity and an equation?",
      answer: [{ type: "paragraph", children: [{ text: "An identity is true for all inputs where both sides are defined; an equation is solved only for specific inputs." }] }],
    },
    {
      question: "Are general solutions and addition/multiple-angle formulae explicit in JEE Advanced 2026?",
      answer: [{ type: "paragraph", children: [{ text: "Yes. JEE Advanced 2026 explicitly includes periodicity, graphs, addition and subtraction formulae, multiple and sub-multiple angle formulae, and general solutions of trigonometric equations." }] }],
    },
  ],

  sources: ["nta-jee-syllabus", "jee-advanced-syllabus", "nta-jee-main-2026-syllabus-pdf", "ncert-math-exemplar"],
  sourceNote:
    "Use only official Main and Advanced syllabus documents for scope claims and verified NCERT exemplar material for supporting mathematics. No frequency, weightage or expected-question claim is published.",
  contributorPolicy: [
    "Written by: unassigned. Ideal author type: JEE Mathematics education editor.",
    "Academically reviewed by: unassigned. Reviewer specialisation: Algebra and Trigonometry. Minimum qualification: postgraduate Mathematics, Applied Mathematics or equivalent.",
    "Review scope: all function domains, identity conditions, periodic solution families, zero-division protection, graph statements and Main/Advanced boundary.",
  ],

  contentStatus: "draft",

  meta: {
    title: "Trigonometry for JEE 2026: Identities, Equations and Graphs",
    description:
      "Learn JEE trigonometric functions, domains, identities, periodicity, equations and transformation methods with zero-denominator safeguards.",
    ogTitle: "Trigonometry for JEE 2026",
    ogDescription: "Function domains, identities, general solutions and equation-solving traps for JEE Main and Advanced.",
    ogType: "article",
  },
};
