import type { ChapterContent } from "@/content/types";

/**
 * Photosynthesis — T06 production content (N03-02).
 *
 * Focused NEET UG 2026 page: pigments/light capture, photochemical
 * reactions, cyclic/non-cyclic photophosphorylation, chemiosmosis, carbon
 * fixation, C3/C4 relationships, photorespiration and limiting factors.
 *
 * Evidence discipline: no weightage, PYQ frequency, question counts or
 * predictions are asserted. No free-standing ATP/NADPH stoichiometric
 * shortcut number is included. contentStatus stays "draft" pending academic
 * review; no reviewer/author id exists yet.
 */
export const neetBiologyPhotosynthesis: ChapterContent = {
  exam: "NEET",
  platform: "neet",
  subject: "Biology",
  subjectSlug: "biology",
  chapter: "Photosynthesis",
  slug: "photosynthesis",
  url: "/neet/biology/photosynthesis",
  canonicalIntent:
    "Separate pigment and light-capture, photochemical reactions, cyclic/non-cyclic photophosphorylation, chemiosmosis, carbon fixation, C3/C4 relationships, photorespiration and factor limitation for the current NEET UG 2026 photosynthesis scope.",

  heroChips: [
    "Current NEET UG 2026 official scope",
    "Cyclic vs non-cyclic and C3 vs C4 relationships mapped explicitly",
    "No unsupported ATP/NADPH stoichiometric shortcuts",
  ],

  directAnswer: [
    {
      type: "paragraph",
      children: [
        {
          text: "The NEET UG 2026 photosynthesis scope includes the site and pigments of photosynthesis, photochemical and biosynthetic phases, cyclic and non-cyclic photophosphorylation, chemiosmosis, photorespiration, C3 and C4 pathways and factors affecting photosynthesis.",
        },
      ],
    },
    {
      type: "paragraph",
      children: [
        {
          text: "Learn it by tracking compartment, electron flow, ATP/NADPH role, carbon fixation and the conditions that distinguish C3 from C4 behaviour.",
        },
      ],
    },
    {
      type: "note",
      tone: "info",
      children: [
        {
          text: "This page does not publish invented weightage, expected question counts or trend percentages, and does not include an unsupported ATP/NADPH shortcut number.",
        },
      ],
    },
  ],

  prerequisites: [
    {
      label: "Cell Biology",
      url: "/neet/biology/cell-biology",
      relation: "prerequisite",
      description: "Chloroplast structure (thylakoid, stroma) underlies the compartment reasoning used here.",
    },
    {
      label: "Biomolecules",
      url: "/neet/biology/biomolecules",
      relation: "prerequisite",
      description: "Basic understanding of carbohydrates and enzymes supports carbon-fixation reasoning.",
    },
    {
      label: "Plant Physiology",
      url: "/neet/biology/plant-physiology",
      relation: "up",
      description: "Current Unit 4 umbrella that routes to this focused Photosynthesis page.",
    },
  ],

  syllabusMapping: {
    unit: "Unit 4, Plant Physiology",
    topics: [
      "Site and pigments of photosynthesis",
      "Photochemical and biosynthetic phases",
      "Cyclic and non-cyclic photophosphorylation",
      "Chemiosmotic hypothesis",
      "Calvin cycle (carbon fixation)",
      "Photorespiration",
      "C3 and C4 pathways",
      "Factors affecting photosynthesis",
    ],
    syllabusUrl: "/neet/syllabus/biology",
  },

  conceptBlocks: [
    {
      id: "site-and-compartments",
      title: "1. Separate the thylakoid and stroma roles",
      keyIdea: "The biosynthetic phase is not light-dependent directly, but it depends on ATP and NADPH from the photochemical phase.",
      body: [
        {
          type: "paragraph",
          children: [
            {
              text: "Leaves are the principal photosynthetic organs in higher plants, and mesophyll chloroplasts are the main cellular sites. The thylakoid membrane hosts the pigment systems, electron transport and light-driven ATP/reducing-power formation. The stroma hosts the carbon-fixation reactions of the Calvin cycle.",
            },
          ],
        },
        {
          type: "paragraph",
          children: [
            {
              text: "The biosynthetic phase is not correctly understood as a process that \"needs darkness\". It does not directly use light, but it depends on ATP and NADPH generated by the photochemical phase.",
            },
          ],
        },
      ],
    },
    {
      id: "pigments-and-photosystems",
      title: "2. Chlorophyll a is the reaction-centre pigment; PSII and PSI have distinct reaction centres",
      body: [
        {
          type: "paragraph",
          children: [
            {
              text: "Chlorophyll a is the chief reaction-centre pigment. Accessory pigments such as chlorophyll b and carotenoids broaden absorption and transfer excitation energy; carotenoids also have protective roles. Photosystem II has reaction centre P680, and Photosystem I has reaction centre P700.",
            },
          ],
        },
      ],
    },
    {
      id: "non-cyclic-electron-flow",
      title: "3. Trace non-cyclic electron flow from water to reducing power",
      keyIdea: "H2O -> PSII -> electron carriers/proton gradient -> PSI -> reducing power.",
      body: [
        {
          type: "list",
          ordered: true,
          items: [
            [{ text: "Light excites PSII." }],
            [{ text: "Water supplies replacement electrons; water splitting releases O2 and protons." }],
            [{ text: "Electrons pass through carriers that contribute to a thylakoid proton gradient." }],
            [{ text: "Electrons reach PSI and are re-excited." }],
            [{ text: "Terminal reduction produces reducing power for carbon fixation." }],
            [{ text: "Proton flow through ATP synthase drives ATP formation." }],
          ],
        },
      ],
    },
    {
      id: "cyclic-photophosphorylation",
      title: "4. Cyclic photophosphorylation produces ATP only, using PSI alone",
      body: [
        {
          type: "paragraph",
          children: [
            {
              text: "Cyclic flow uses PSI and returns excited electrons through carriers rather than using the non-cyclic terminal reduction route. ATP can be produced. NADPH is not produced by the cyclic route, and O2 is not released by this cycle because PSII water splitting is not part of it.",
            },
          ],
        },
      ],
    },
    {
      id: "chemiosmotic-hypothesis",
      title: "5. ATP forms through a proton gradient, not directly from electrons",
      keyIdea: "electron transfer -> proton gradient -> proton flow through ATP synthase -> ATP.",
      body: [
        {
          type: "paragraph",
          children: [
            {
              text: "Electron transport and water-splitting relationships contribute to proton accumulation on the thylakoid lumen side. Protons return through ATP synthase, and the released gradient energy drives phosphorylation. The relationship 'electrons make ATP directly' is not correct.",
            },
          ],
        },
      ],
    },
    {
      id: "calvin-cycle",
      title: "6. The Calvin cycle has carboxylation, reduction and regeneration stages",
      body: [
        {
          type: "list",
          ordered: true,
          items: [
            [{ text: "Carboxylation: ", bold: true }, { text: "RuBisCO adds CO2 to RuBP, producing an unstable intermediate that yields 3-PGA." }],
            [{ text: "Reduction: ", bold: true }, { text: "ATP and NADPH support conversion toward carbohydrate intermediates." }],
            [{ text: "Regeneration: ", bold: true }, { text: "RuBP is regenerated so fixation can continue." }],
          ],
        },
        {
          type: "note",
          tone: "caution",
          children: [{ text: "No free-standing ATP/NADPH shortcut number is included. Any stoichiometric worked example requires exact source-defined accounting plus academic sign-off." }],
        },
      ],
    },
    {
      id: "photorespiration",
      title: "7. Photorespiration is a distinct RuBisCO-oxygenase pathway",
      body: [
        {
          type: "paragraph",
          children: [
            {
              text: "RuBisCO can act as an oxygenase as well as a carboxylase. In C3 plants, oxygenation of RuBP initiates photorespiration. It consumes resources without producing sugar or ATP as the photosynthetic carbon-fixation route does. Photorespiration should not be called \"ordinary respiration in light\"; it is a distinct pathway initiated by RuBisCO oxygenase activity.",
            },
          ],
        },
      ],
    },
    {
      id: "c3-vs-c4",
      title: "8. C4 is a CO2-concentrating pre-fixation system, not a Calvin-cycle replacement",
      body: [
        {
          type: "paragraph",
          children: [
            {
              text: "C3 plants use the Calvin cycle as the primary fixation path; the first stable product is a 3-carbon compound. C4 plants initially fix carbon in mesophyll cells into a 4-carbon compound, transfer carbon to bundle-sheath cells and release CO2 near RuBisCO, where the Calvin cycle operates. This arrangement reduces the impact of photorespiration under relevant conditions.",
            },
          ],
        },
      ],
    },
    {
      id: "factors-affecting-photosynthesis",
      title: "9. Apply Blackman's limiting-factor principle",
      keyIdea: "Raising a non-limiting factor may have little effect on the rate.",
      body: [
        {
          type: "paragraph",
          children: [
            {
              text: "Important external factors include light, CO2, temperature and water. Internal plant factors also matter. Blackman's limiting-factor principle states that when several factors affect a process, the rate is constrained by the factor nearest its limiting level.",
            },
          ],
        },
      ],
    },
  ],

  tables: [
    {
      id: "process-location-input-output",
      slot: "concepts",
      heading: "Process, location, input and output matrix",
      jump: true,
      columns: ["Process", "Main location", "Driver/input", "Output/relationship", "Confusion control"],
      rows: [
        ["Light harvesting", "Thylakoid pigment systems", "Photons", "Excited reaction-centre electrons", "Not carbon fixation"],
        ["Water splitting", "PSII-associated thylakoid context", "H2O + PSII photochemistry", "Electrons, protons, O2", "Photosynthetic O2 comes from water"],
        ["Non-cyclic photophosphorylation", "Thylakoid", "PSII + PSI flow", "ATP + reducing power; O2 via water splitting", "Distinct from cyclic"],
        ["Cyclic photophosphorylation", "PSI-associated thylakoid route", "Light + PSI", "ATP only from this route", "No PSII water splitting/NADPH endpoint"],
        ["Calvin cycle", "Stroma", "CO2, RuBP, ATP, NADPH", "Carbon fixation + RuBP regeneration", "Not darkness-dependent"],
        ["Photorespiration", "Initiated by RuBisCO oxygenase", "RuBP + O2", "Resource-consuming recovery pathway", "Not mitochondrial respiration"],
        ["C4 pre-fixation", "Mesophyll then bundle-sheath delivery", "Inorganic carbon", "4-C acid -> CO2 delivery -> Calvin cycle", "Calvin cycle still present"],
      ],
    },
    {
      id: "cyclic-vs-non-cyclic",
      slot: "concepts",
      heading: "Cyclic vs non-cyclic photophosphorylation",
      jump: true,
      columns: ["Dimension", "Cyclic", "Non-cyclic"],
      rows: [
        ["Photosystems", "PSI", "PSII + PSI"],
        ["Electron endpoint", "Returns to carrier chain", "Terminal reduction route"],
        ["ATP", "Yes", "Yes"],
        ["NADPH", "No, not from the cyclic route", "Yes"],
        ["O2 release", "No PSII water-splitting O2 in this cycle", "Yes, associated with PSII water splitting"],
      ],
    },
    {
      id: "c3-vs-c4-matrix",
      slot: "concepts",
      heading: "C3 vs C4 matrix",
      jump: true,
      columns: ["Dimension", "C3", "C4"],
      rows: [
        ["First stable product", "3-carbon", "4-carbon"],
        ["Initial fixation", "Mesophyll Calvin context", "Mesophyll C4 pre-fixation"],
        ["Calvin cycle", "Present", "Present, in bundle-sheath cells"],
        ["CO2 concentration near RuBisCO", "No dedicated C4 step", "Enhanced by C4 transfer/release"],
        ["Photorespiration", "More exposed under relevant conditions", "Reduced by the CO2-concentrating mechanism"],
      ],
    },
  ],

  mistakes: [
    {
      id: "calvin-cycle-darkness",
      mistake: "Assuming the Calvin cycle requires darkness.",
      why: [{ type: "paragraph", children: [{ text: "The cycle is directly light-independent, but it depends on ATP and NADPH generated by the photochemical phase." }] }],
      fix: [{ type: "paragraph", children: [{ text: "State the dependency correctly: not directly light-dependent, but dependent on photochemical products." }] }],
      errorType: "knowledge-gap",
    },
    {
      id: "cyclic-gives-nadph-o2",
      mistake: "Believing cyclic flow gives NADPH and releases O2.",
      why: [{ type: "paragraph", children: [{ text: "Cyclic PSI flow produces ATP only; it has no PSII water splitting and no terminal NADPH-forming reduction step." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Recheck the cyclic-vs-non-cyclic matrix before assigning NADPH or O2 output to the cyclic route." }] }],
      errorType: "recall-gap",
    },
    {
      id: "c4-lacks-calvin-cycle",
      mistake: "Assuming C4 plants lack the Calvin cycle.",
      why: [{ type: "paragraph", children: [{ text: "C4 is a CO2-concentrating pre-fixation system; the Calvin cycle still occurs, in the bundle-sheath cells." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Trace the full C4 relationship: mesophyll pre-fixation -> bundle-sheath CO2 delivery -> Calvin cycle." }] }],
      errorType: "knowledge-gap",
    },
    {
      id: "photorespiration-as-normal-respiration",
      mistake: "Treating photorespiration as normal respiration occurring in daylight.",
      why: [{ type: "paragraph", children: [{ text: "Photorespiration is a distinct pathway initiated by RuBisCO acting as an oxygenase, not mitochondrial cellular respiration." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Link photorespiration explicitly to RuBisCO oxygenase activity rather than to general cellular respiration." }] }],
      errorType: "decision-error",
    },
    {
      id: "more-of-any-factor-raises-rate",
      mistake: "Assuming more of any single factor always raises the photosynthetic rate.",
      why: [{ type: "paragraph", children: [{ text: "Blackman's limiting-factor principle means the rate is constrained by the factor nearest its limiting level; raising a non-limiting factor may have little effect." }] }],
      fix: [{ type: "paragraph", children: [{ text: "Identify which factor is limiting in the given scenario before deciding whether increasing another factor changes the rate." }] }],
      errorType: "execution-error",
    },
  ],

  relatedChapters: [
    {
      label: "Plant Physiology",
      url: "/neet/biology/plant-physiology",
      relation: "up",
      description: "Current Unit 4 umbrella; integrates photosynthesis with respiration and Growth and Development.",
    },
    {
      label: "Respiration in Plants",
      url: "/neet/biology/respiration-in-plants",
      relation: "related",
      description: "Complementary process using organic substrates produced through photosynthesis.",
    },
    {
      label: "Cell Biology",
      url: "/neet/biology/cell-biology",
      relation: "prerequisite",
      description: "Chloroplast structure underlies the thylakoid/stroma compartment reasoning used here.",
    },
    {
      label: "Biomolecules",
      url: "/neet/biology/biomolecules",
      relation: "prerequisite",
      description: "Carbohydrate and enzyme background used for carbon-fixation reasoning.",
    },
  ],

  links: [
    {
      label: "Biology syllabus",
      url: "/neet/syllabus/biology",
      relation: "up",
      description: "Exam-level official Biology syllabus mapping.",
    },
  ],

  sources: ["nta-neet-2026-bulletin", "nmc-neet-ug-2026-syllabus", "ncert-biology-11-contents"],
  sourceNote:
    "Paraphrased from the current NCERT Photosynthesis in Higher Plants chapter (Class XI). Relationships among photosystems, proton gradient, Calvin cycle, photorespiration, C4 pathway and limiting factors are retained without copying NCERT diagrams or long passages. University-level kinetics, detailed carbon-metabolism extensions and unsupported ATP/NADPH shortcut numbers are excluded unless separately approved.",
  contributorPolicy: [
    "Written by: UNASSIGNED",
    "Academically reviewed by: UNASSIGNED",
    "Last reviewed: pending human review",
    "Sources checked: visible in page source register",
  ],

  faqs: [
    {
      question: "What is the key difference between cyclic and non-cyclic photophosphorylation?",
      answer: [
        {
          type: "paragraph",
          children: [
            {
              text: "Cyclic PSI flow produces ATP without NADPH or PSII-linked oxygen release; non-cyclic flow uses PSII and PSI and supports ATP, reducing power and O2 evolution from water splitting.",
            },
          ],
        },
      ],
    },
    {
      question: "Do C4 plants use the Calvin cycle?",
      answer: [{ type: "paragraph", children: [{ text: "Yes. C4 plants concentrate CO2 first and then use the Calvin cycle in bundle-sheath cells." }] }],
    },
    {
      question: "What initiates photorespiration?",
      answer: [{ type: "paragraph", children: [{ text: "RuBisCO acting as an oxygenase and oxygenating RuBP." }] }],
    },
  ],

  contentStatus: "draft",
  meta: {
    title: "NEET Photosynthesis 2026: Light Reactions, C3, C4, Photorespiration",
    description:
      "Learn the verified NEET UG 2026 photosynthesis scope through process maps for photosystems, photophosphorylation, chemiosmosis, Calvin cycle, C3/C4 and limiting factors.",
  },
};
