import heroStudent from "@/assets/hero-student.jpg";
import ndaAspirant from "@/assets/nda-aspirant.jpg";
import parentChild from "@/assets/parent-child.jpg";
import voiceAspirant from "@/assets/voice-aspirant.jpg";
import voiceEducator from "@/assets/voice-educator.jpg";
import voiceParent from "@/assets/voice-parent.jpg";
import type { BlogArticle, BlogContentNode, BlogExam } from "./types";

// DEVELOPMENT / DESIGN PLACEHOLDER DATA
// These six concise records exist only to verify the frontend. They contain no
// invented people, publication history, exam statistics, weightage or claims.

const internalRoutes: Record<BlogExam, string[]> = {
  JEE: ["/jee/syllabus", "/jee/physics", "/jee/previous-year-papers"],
  NEET: ["/neet/syllabus", "/neet/biology", "/neet/previous-year-papers"],
  NDA: ["/nda/syllabus", "/nda/ssb-interview", "/nda/previous-year-papers"],
  GENERAL: ["/jee", "/neet", "/nda"],
};

function body(exam: BlogExam, focus: string): BlogContentNode[] {
  const firstRoute = internalRoutes[exam][0] ?? "/";
  return [
    {
      type: "paragraph",
      children: [{ text: `This development article demonstrates how Rank Sarthi can present ${focus} without turning unverified assumptions into guidance.` }],
    },
    { type: "heading", level: 2, id: "start-with-the-source", text: "Start with the source" },
    {
      type: "paragraph",
      children: [
        { text: "Begin with the relevant official material, then use the matching " },
        { text: `${exam === "GENERAL" ? "exam" : exam} resource`, bold: true, href: firstRoute },
        { text: " to organise the next step." },
      ],
    },
    { type: "heading", level: 2, id: "review-the-work", text: "Review the work" },
    {
      type: "list",
      ordered: true,
      items: [
        [{ text: "Record what the question or task required." }],
        [{ text: "Separate knowledge gaps from execution and decision errors." }],
        [{ text: "Choose one specific action for the next study session." }],
      ],
    },
    { type: "heading", level: 3, id: "keep-the-record-useful", text: "Keep the record useful" },
    {
      type: "blockquote",
      children: [{ text: "A review is useful when it changes the next decision, not when it only repeats the score." }],
    },
    {
      type: "table",
      caption: "A simple review structure",
      columns: ["Observe", "Classify", "Act"],
      rows: [["What happened", "Why it happened", "What changes next"]],
    },
    {
      type: "callout",
      title: "Development note",
      children: [{ text: "This is short placeholder editorial copy for interface testing, not exam advice." }],
    },
  ];
}

export const localBlogArticles: BlogArticle[] = [
  {
    id: "local-jee-unit-map",
    slug: "jee-main-physics-syllabus-unit-map",
    title: "JEE Main Physics Syllabus: Using the Official Unit Map",
    excerpt: "A source-first way to turn a syllabus map into a practical chapter review sequence.",
    content: body("JEE", "an official syllabus unit map"),
    featuredImage: heroStudent,
    featuredImageAlt: "Student reviewing notes at a study desk",
    primaryExam: "JEE",
    category: "JEE",
    tags: ["Syllabus", "Physics"],
    author: null,
    reviewer: null,
    reviewStatus: "REVIEW_PENDING",
    sources: [],
    relatedArticleSlugs: ["jee-main-vs-jee-advanced-preparation-depth", "previous-year-papers-without-inventing-weightage"],
    relatedInternalRoutes: internalRoutes.JEE,
    seoTitle: "Using the JEE Physics Syllabus Unit Map | Rank Sarthi",
    metaDescription: "A development article showing a source-first approach to using the JEE Physics syllabus unit map.",
    canonicalOverride: null,
    featured: true,
    status: "draft",
  },
  {
    id: "local-neet-review",
    slug: "review-errors-after-neet-practice",
    title: "How to Review Errors After a NEET Practice Session",
    excerpt: "A lightweight review loop for separating knowledge, recall, execution and decision errors.",
    content: body("NEET", "practice-session review"),
    featuredImage: voiceAspirant,
    featuredImageAlt: "Aspirant reflecting on a practice session",
    primaryExam: "NEET",
    category: "NEET",
    tags: ["Error Review", "Practice"],
    author: null,
    reviewer: null,
    reviewStatus: "REVIEW_PENDING",
    sources: [],
    relatedArticleSlugs: ["previous-year-papers-without-inventing-weightage", "human-review-pending-on-rank-sarthi"],
    relatedInternalRoutes: internalRoutes.NEET,
    seoTitle: "Reviewing Errors After NEET Practice | Rank Sarthi",
    metaDescription: "A development article demonstrating a clear review loop after a NEET practice session.",
    canonicalOverride: null,
    featured: false,
    status: "draft",
  },
  {
    id: "local-nda-stages",
    slug: "nda-written-exam-and-ssb-two-stages",
    title: "NDA Written Exam and SSB: Understanding the Two Stages",
    excerpt: "A simple editorial structure for keeping written-exam preparation and later selection stages distinct.",
    content: body("NDA", "the two-stage NDA journey"),
    featuredImage: ndaAspirant,
    featuredImageAlt: "NDA aspirant preparing outdoors",
    primaryExam: "NDA",
    category: "NDA",
    tags: ["Written Exam", "SSB"],
    author: null,
    reviewer: null,
    reviewStatus: "REVIEW_PENDING",
    sources: [],
    relatedArticleSlugs: ["previous-year-papers-without-inventing-weightage"],
    relatedInternalRoutes: internalRoutes.NDA,
    seoTitle: "NDA Written Exam and SSB Stages | Rank Sarthi",
    metaDescription: "A development article showing how the NDA written exam and SSB stages can be explained distinctly.",
    canonicalOverride: null,
    featured: false,
    status: "draft",
  },
  {
    id: "local-jee-depth",
    slug: "jee-main-vs-jee-advanced-preparation-depth",
    title: "JEE Main vs JEE Advanced: Why Preparation Depth Differs",
    excerpt: "A neutral framework for reading each exam's official scope before choosing study depth.",
    content: body("JEE", "differences in preparation depth"),
    featuredImage: voiceEducator,
    featuredImageAlt: "Educator reviewing an academic plan",
    primaryExam: "JEE",
    category: "Preparation Strategy",
    tags: ["JEE Main", "JEE Advanced"],
    author: null,
    reviewer: null,
    reviewStatus: "REVIEW_PENDING",
    sources: [],
    relatedArticleSlugs: ["jee-main-physics-syllabus-unit-map"],
    relatedInternalRoutes: internalRoutes.JEE,
    seoTitle: "JEE Main and Advanced Preparation Depth | Rank Sarthi",
    metaDescription: "A development article demonstrating how to frame JEE Main and Advanced preparation depth without invented claims.",
    canonicalOverride: null,
    featured: false,
    status: "draft",
  },
  {
    id: "local-pyq-method",
    slug: "previous-year-papers-without-inventing-weightage",
    title: "How to Use Previous-Year Papers Without Inventing Weightage",
    excerpt: "Use past papers as evidence for review while keeping unsupported frequency claims out of the plan.",
    content: body("GENERAL", "previous-year paper review"),
    featuredImage: parentChild,
    featuredImageAlt: "Learners discussing a preparation plan",
    primaryExam: "GENERAL",
    category: "Study Resources",
    tags: ["Previous-Year Papers", "Review"],
    author: null,
    reviewer: null,
    reviewStatus: "REVIEW_PENDING",
    sources: [],
    relatedArticleSlugs: ["review-errors-after-neet-practice", "human-review-pending-on-rank-sarthi"],
    relatedInternalRoutes: internalRoutes.GENERAL,
    seoTitle: "Using Previous-Year Papers Carefully | Rank Sarthi",
    metaDescription: "A development article demonstrating evidence-led previous-year paper review without invented weightage.",
    canonicalOverride: null,
    featured: false,
    status: "draft",
  },
  {
    id: "local-review-status",
    slug: "human-review-pending-on-rank-sarthi",
    title: "What Human Review Pending Means on Rank Sarthi",
    excerpt: "Why draft editorial material stays clearly labelled until its review and publication gates are complete.",
    content: body("GENERAL", "the human-review state"),
    featuredImage: voiceParent,
    featuredImageAlt: "Reader considering preparation information",
    primaryExam: "GENERAL",
    category: "Exam Updates",
    tags: ["Editorial Policy", "Trust"],
    author: null,
    reviewer: null,
    reviewStatus: "REVIEW_PENDING",
    sources: [],
    relatedArticleSlugs: ["previous-year-papers-without-inventing-weightage"],
    relatedInternalRoutes: internalRoutes.GENERAL,
    seoTitle: "Human Review Pending on Rank Sarthi",
    metaDescription: "A development article explaining the visible human-review-pending state used by Rank Sarthi.",
    canonicalOverride: null,
    featured: false,
    status: "draft",
  },
];