import type { FreshDataRecord, FreshnessChangeLogEntry } from "./types";

/**
 * Approved FreshDataRecords. Every entry here has passed the review gate:
 * `reviewStatus: "APPROVED"`. Nothing enters this file automatically — the
 * watcher writes change CANDIDATES, a human approves, only then does the
 * public value move.
 */
export const freshDataRecords: FreshDataRecord[] = [
  {
    id: "jee-main-2026-paper-archive",
    pageUrl: "/jee/previous-year-papers",
    platform: "JEE",
    exam: "JEE Main",
    cycle: "2026",
    field: "officialPaperArchive",
    fieldLabel: "Official JEE Main 2026 Paper 1 files",
    currentValue: "9 of 19 verified Paper 1 events have an authority-hosted paper file",
    status: "VERIFIED",
    sourceRef: "NTA-DOCS",
    sourceUrl: "https://jeemain.nta.nic.in/documents/",
    sourceAuthority: "National Testing Agency",
    lastChecked: "2026-09-11",
    lastVerified: "2026-09-11",
    refreshCadence: "WEEKLY",
    refreshTrigger: ["new question-paper menu entry", "archive reorganisation"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Official source could not be rechecked. Pending rows stay inactive and no substitute copy is shown.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-main-2026-s1-p1-final-key",
    pageUrl: "/jee/answer-key",
    platform: "JEE",
    exam: "JEE Main",
    cycle: "2026",
    field: "finalAnswerKey",
    fieldLabel: "JEE Main 2026 Session 1 Paper 1 final answer key",
    currentValue: "Published 16 February 2026",
    status: "VERIFIED",
    sourceRef: "NTA-FINAL-KEY-S1-P1-2026",
    sourceUrl: "https://cdnbbsr.s3waas.gov.in/s3f8e59f4b2fe7c5705bf878bbd494ccdf/uploads/2026/02/20260216459398513.pdf",
    sourceAuthority: "National Testing Agency",
    lastChecked: "2026-09-11",
    lastVerified: "2026-09-11",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["key revision", "withdrawal", "official URL change"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Official key document could not be rechecked. The last verified key record is preserved.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-main-2026-advanced-eligibility-threshold",
    pageUrl: "/jee/cutoff",
    platform: "JEE",
    exam: "JEE Main",
    cycle: "2026",
    field: "advancedEligibilityThreshold",
    fieldLabel: "JEE Main 2026 Advanced-eligibility NTA Score",
    currentValue: "UR-ALL lower boundary NTA Score 93.4123549",
    status: "VERIFIED",
    sourceRef: "NTA-RESULT-NOTICE-2026",
    sourceUrl: "https://www.nta.ac.in/Download/Notice/Notice_20260420194021.pdf",
    sourceAuthority: "National Testing Agency",
    lastChecked: "2026-09-11",
    lastVerified: "2026-09-11",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["result notice correction", "new cycle result"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Official notice could not be rechecked. The last verified threshold table is preserved.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-main-2026-cycle-timeline",
    pageUrl: "/jee/exam-dates",
    platform: "JEE",
    exam: "JEE Main",
    cycle: "2026",
    field: "cycleTimeline",
    fieldLabel: "JEE Main 2026 session milestones",
    currentValue: "Session 1 result 16 February 2026; Session 2 result 20 April 2026",
    status: "VERIFIED",
    sourceRef: "NTA-PUBLIC-NOTICES",
    sourceUrl: "https://jeemain.nta.nic.in/public-notices/",
    sourceAuthority: "National Testing Agency",
    lastChecked: "2026-09-11",
    lastVerified: "2026-09-11",
    refreshCadence: "WEEKLY",
    refreshTrigger: ["schedule correction notice", "new cycle notice"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Official notice index could not be rechecked. The last verified milestones are preserved.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-advanced-2026-paper-archive",
    pageUrl: "/jee/jee-advanced/previous-year-papers",
    platform: "JEE",
    exam: "JEE Advanced",
    cycle: "2026",
    field: "officialPaperArchive",
    fieldLabel: "Official JEE Advanced paper archive",
    currentValue: "2007 to 2025 archive plus 2026 Paper 1 and Paper 2 in English and Hindi",
    status: "VERIFIED",
    sourceRef: "ADV-ARCHIVE",
    sourceUrl: "https://jeeadv.ac.in/archive.html",
    sourceAuthority: "JEE Advanced official organising authority",
    lastChecked: "2026-09-11",
    lastVerified: "2026-09-11",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["new cycle papers", "archive URL change"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Official archive could not be rechecked. Unverified files stay inactive.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-main-2027-schedule-status",
    pageUrl: "/jee/exam-dates",
    platform: "JEE",
    exam: "JEE Main",
    cycle: "2027",
    field: "scheduleStatus",
    fieldLabel: "JEE Main 2027 schedule",
    currentValue: "Not officially announced",
    status: "NOT_ANNOUNCED",
    sourceRef: "NTA-HOME",
    sourceUrl: "https://jeemain.nta.nic.in/",
    sourceAuthority: "National Testing Agency",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "DAILY",
    refreshTrigger: ["new information bulletin", "new application notice", "schedule correction"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "SHOW_NOT_ANNOUNCED",
      publicMessage: "Official source could not be rechecked. No unverified date has been added.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-advanced-2027-schedule-status",
    pageUrl: "/jee/exam-dates",
    platform: "JEE",
    exam: "JEE Advanced",
    cycle: "2027",
    field: "scheduleStatus",
    fieldLabel: "JEE Advanced 2027 schedule",
    currentValue: "Not officially announced",
    status: "NOT_ANNOUNCED",
    sourceRef: "ADV-HOME-2026",
    sourceUrl: "https://jeeadv.ac.in/",
    sourceAuthority: "JEE Advanced official organising authority",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "DAILY",
    refreshTrigger: ["new organising site", "examination date", "information brochure"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "SHOW_NOT_ANNOUNCED",
      publicMessage: "Official source could not be rechecked. No unverified date has been added.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-main-2026-s2-p1-final-key",
    pageUrl: "/jee/answer-key",
    platform: "JEE",
    exam: "JEE Main",
    cycle: "2026",
    field: "answerKeyState",
    fieldLabel: "JEE Main 2026 Session 2 Paper 1 answer key",
    currentValue: "Final answer key available for Session 2 Paper 1",
    status: "VERIFIED",
    sourceRef: "NTA-FINAL-KEY-S2-P1-2026",
    sourceUrl:
      "https://cdnbbsr.s3waas.gov.in/s3f8e59f4b2fe7c5705bf878bbd494ccdf/uploads/2026/04/20260420409057044.pdf",
    sourceAuthority: "National Testing Agency",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["revised key", "withdrawal", "official URL change"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Last verified final key retained; official file could not be rechecked.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-advanced-2026-final-keys",
    pageUrl: "/jee/answer-key",
    platform: "JEE",
    exam: "JEE Advanced",
    cycle: "2026",
    field: "answerKeyState",
    fieldLabel: "JEE Advanced 2026 final answer keys",
    currentValue: "Final answer keys available for Paper 1 and Paper 2",
    status: "VERIFIED",
    sourceRef: "ADV-HOME-2026",
    sourceUrl: "https://jeeadv.ac.in/",
    sourceAuthority: "JEE Advanced 2026 organising authority, IIT Roorkee",
    publishedAt: "2026-06-01T14:45:00+05:30",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["revised key", "withdrawal", "official URL change"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Last verified final-key status retained; check the official authority before acting.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-advanced-2026-crl-qualifying-marks",
    pageUrl: "/jee/cutoff",
    platform: "JEE",
    exam: "JEE Advanced",
    cycle: "2026",
    field: "qualifyingMarks.commonRankList",
    fieldLabel: "JEE Advanced 2026 Common Rank List qualifying marks",
    currentValue: { minimumEachSubject: 8, minimumAggregate: 92 },
    status: "VERIFIED",
    sourceRef: "ADV-CUTOFF-2026",
    sourceUrl: "https://jeeadv.ac.in/documents/cutoffs_2026.pdf",
    sourceAuthority: "JEE Advanced 2026 organising authority",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["corrected qualifying marks", "replacement PDF"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Last verified 2026 table retained; official source recheck is pending.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "jee-2026-rank-sarthi-analysis-status",
    pageUrl: "/jee/analysis",
    platform: "JEE",
    exam: "JEE Main and JEE Advanced",
    cycle: "2026",
    field: "rankSarthiAnalysisStatus",
    fieldLabel: "Rank Sarthi analysis readiness",
    currentValue: "No approved analysed dataset supplied",
    status: "VERIFIED",
    sourceRef: "INTERNAL-DATASET-REGISTER",
    sourceUrl: "https://ranksarthi.com/jee/analysis",
    sourceAuthority: "Rank Sarthi editorial control",
    lastChecked: "2026-09-09",
    lastVerified: "2026-09-09",
    refreshCadence: "EVENT_TRIGGERED",
    refreshTrigger: ["approved dataset created", "dataset corrected", "dataset withdrawn"],
    confidence: "HIGH",
    changePolicy: "NEVER_AUTO_PUBLISH",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Analysis remains unavailable until a reviewed dataset exists.",
      actionState: "HIDE",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  /* ---------------- NEET R01 (resource + freshness factory) ---------------- */
  {
    id: "neet-2026-reexam-final-key",
    pageUrl: "/neet/answer-key",
    platform: "NEET",
    exam: "NEET (UG)",
    cycle: "2026",
    field: "finalAnswerKeyState",
    fieldLabel: "NEET UG 2026 Re-Examination (21 Jun 2026) final answer key",
    currentValue: "Final answer key published by NTA on 16 July 2026",
    status: "VERIFIED",
    sourceRef: "NEET-2026-REEXAM-FINAL-KEY",
    sourceUrl:
      "https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/07/20260716131467523.pdf",
    sourceAuthority: "National Testing Agency",
    publishedAt: "2026-07-16",
    lastChecked: "2026-09-10",
    lastVerified: "2026-09-10",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["new official key notice", "key correction notice"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage:
        "Official source could not be rechecked. The last verified official key is still shown.",
      actionState: "KEEP",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "neet-2026-original-final-key",
    pageUrl: "/neet/answer-key",
    platform: "NEET",
    exam: "NEET (UG)",
    cycle: "2026",
    field: "finalAnswerKeyState",
    fieldLabel: "NEET UG 2026 examination of 3 May 2026, final answer key",
    currentValue: "Not available / not verified",
    status: "NOT_ANNOUNCED",
    sourceRef: "NEET-HOME",
    sourceUrl: "https://neet.nta.nic.in/",
    sourceAuthority: "National Testing Agency",
    lastChecked: "2026-09-10",
    lastVerified: "2026-09-10",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["official final key notice for the 3 May 2026 event"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "SHOW_NOT_ANNOUNCED",
      publicMessage: "No verified official final key exists for this event. Nothing has been substituted.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "neet-2026-qualifying-cutoff",
    pageUrl: "/neet/cutoff",
    platform: "NEET",
    exam: "NEET (UG)",
    cycle: "2026",
    field: "qualifyingCutoff",
    fieldLabel: "NEET UG 2026 official qualifying cutoff (percentile and marks range)",
    currentValue:
      "UR/EWS 715-213 at the 50th percentile; reserved-category and PwBD thresholds published in the same official table",
    status: "VERIFIED",
    sourceRef: "NEET-KEY-DATA-POINTS",
    sourceUrl:
      "https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/07/202607161539405935.pdf",
    sourceAuthority: "National Testing Agency",
    publishedAt: "2026-07-16",
    lastChecked: "2026-09-10",
    lastVerified: "2026-09-10",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["official result publication", "revised official key-data document"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage:
        "Official source could not be rechecked. The last verified qualifying cutoff is still shown.",
      actionState: "KEEP",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "neet-2026-cycle-timeline",
    pageUrl: "/neet/exam-dates",
    platform: "NEET",
    exam: "NEET (UG)",
    cycle: "2026",
    field: "cycleTimelineState",
    fieldLabel: "NEET UG 2026 cycle status",
    currentValue:
      "Two separate examination events: 3 May 2026 and the 21 June 2026 re-examination. Final key and result published 16 July 2026.",
    status: "VERIFIED",
    sourceRef: "NEET-2026-RESULT-NOTICE",
    sourceUrl:
      "https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/07/20260716477215762.pdf",
    sourceAuthority: "National Testing Agency",
    publishedAt: "2026-07-16",
    lastChecked: "2026-09-10",
    lastVerified: "2026-09-10",
    refreshCadence: "WEEKLY",
    refreshTrigger: ["official notice changing a milestone", "new cycle notification"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage:
        "Official source could not be rechecked. The last verified milestone values are still shown.",
      actionState: "KEEP",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "neet-2027-schedule-status",
    pageUrl: "/neet/exam-dates",
    platform: "NEET",
    exam: "NEET (UG)",
    cycle: "2027",
    field: "scheduleStatus",
    fieldLabel: "NEET UG 2027 schedule",
    currentValue: "Not officially announced",
    status: "NOT_ANNOUNCED",
    sourceRef: "NEET-HOME",
    sourceUrl: "https://neet.nta.nic.in/",
    sourceAuthority: "National Testing Agency",
    lastChecked: "2026-09-10",
    lastVerified: "2026-09-10",
    refreshCadence: "WEEKLY",
    refreshTrigger: ["new information bulletin", "application notice", "schedule notice"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "SHOW_NOT_ANNOUNCED",
      publicMessage: "Official source could not be rechecked. No unverified date has been added.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "neet-official-paper-archive",
    pageUrl: "/neet/previous-year-papers",
    platform: "NEET",
    exam: "NEET (UG)",
    cycle: "2026",
    field: "officialPaperArchiveState",
    fieldLabel: "Authority-hosted NEET question-paper files",
    currentValue:
      "Verified authority-hosted paper files exist for the 2020 examination. No authority-hosted paper file was verified for 2021-2026.",
    status: "SOURCE_AVAILABLE",
    sourceRef: "NEET-ARCHIVE",
    sourceUrl: "https://neet.nta.nic.in/archive/",
    sourceAuthority: "National Testing Agency",
    lastChecked: "2026-09-10",
    lastVerified: "2026-09-10",
    refreshCadence: "EVENT_TRIGGERED",
    refreshTrigger: ["new archive resource", "official paper release after an examination"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage:
        "Official archive could not be rechecked. No third-party file has been promoted to official.",
      actionState: "KEEP",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-i-2026-cycle-timeline",
    pageUrl: "/nda/exam-dates",
    platform: "NDA",
    exam: "NDA & NA (I)",
    cycle: "2026",
    field: "cycleTimeline",
    fieldLabel: "NDA I 2026 official milestones",
    currentValue: "Notification 10 Dec 2025 · application closed 30 Dec 2025 · exam 12 Apr 2026 · question papers 13 Apr 2026 · written result 8 May 2026 · name list 13 May 2026 · cutoff and final result not yet published",
    status: "VERIFIED",
    sourceRef: "UPSC-NDA-I-2026-PAGE",
    sourceUrl: "https://www.upsc.gov.in/examinations/National%20Defence%20Academy%20and%20Naval%20Academy%20Examination%20%28I%29%2C%202026",
    sourceAuthority: "Union Public Service Commission",
    publishedAt: "2026-05-13",
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "WEEKLY",
    refreshTrigger: ["new document row", "final result publication"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Official examination page could not be rechecked. The last verified NDA I 2026 milestones are preserved.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-ii-2026-cycle-timeline",
    pageUrl: "/nda/exam-dates",
    platform: "NDA",
    exam: "NDA & NA (II)",
    cycle: "2026",
    field: "cycleTimeline",
    fieldLabel: "NDA II 2026 official milestones",
    currentValue: "Notification 20 May 2026 · application closed 11 Jun 2026 · time table 12 Aug 2026 · e-Admit Card 3 Sep 2026 · exam scheduled 13 Sep 2026 · question papers, answer key, result, cutoff and merit not yet published",
    status: "VERIFIED",
    sourceRef: "UPSC-NDA-II-2026-PAGE",
    sourceUrl: "https://www.upsc.gov.in/examinations/National%20Defence%20Academy%20and%20Naval%20Academy%20Examination%20%28II%29%2C%202026",
    sourceAuthority: "Union Public Service Commission",
    publishedAt: "2026-09-03",
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "DAILY",
    refreshTrigger: ["question-paper upload", "result notice", "new press note"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Official examination page could not be rechecked. The last verified NDA II 2026 milestones are preserved.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-i-2026-paper-archive",
    pageUrl: "/nda/previous-year-papers",
    platform: "NDA",
    exam: "NDA & NA (I)",
    cycle: "2026",
    field: "officialPaperArchive",
    fieldLabel: "Official NDA I 2026 question papers",
    currentValue: "Mathematics and General Ability Test papers are available as official UPSC PDFs, uploaded 13 April 2026",
    status: "VERIFIED",
    sourceRef: "UPSC-PREVIOUS-PAPERS",
    sourceUrl: "https://www.upsc.gov.in/examinations/previous-question-papers",
    sourceAuthority: "Union Public Service Commission",
    publishedAt: "2026-04-13",
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["archive reorganisation", "official URL change"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "The official paper library could not be rechecked. Verified paper records are preserved and no substitute copy is shown.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-ii-2026-paper-publication",
    pageUrl: "/nda/previous-year-papers",
    platform: "NDA",
    exam: "NDA & NA (II)",
    cycle: "2026",
    field: "officialPaperPublication",
    fieldLabel: "Official NDA II 2026 question papers",
    currentValue: "Not published by UPSC as of 12 September 2026; examination scheduled 13 September 2026",
    status: "NOT_ANNOUNCED",
    sourceRef: "UPSC-PREVIOUS-PAPERS",
    sourceUrl: "https://www.upsc.gov.in/examinations/previous-question-papers",
    sourceAuthority: "Union Public Service Commission",
    
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "DAILY",
    refreshTrigger: ["new NDA II 2026 paper row", "exam-page document upload"],
    confidence: "HIGH",
    changePolicy: "NEVER_AUTO_PUBLISH",
    fallback: {
      publicValue: "SHOW_NOT_ANNOUNCED",
      publicMessage: "No official NDA II 2026 paper exists yet. Paper actions stay inactive until a verified official source is approved.",
      actionState: "HIDE",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-i-2026-written-result",
    pageUrl: "/nda/result",
    platform: "NDA",
    exam: "NDA & NA (I)",
    cycle: "2026",
    field: "writtenResult",
    fieldLabel: "NDA I 2026 written result",
    currentValue: "Written result published 8 May 2026; written result with names published 13 May 2026; qualification is for the SSB stage only",
    status: "VERIFIED",
    sourceRef: "UPSC-NDA-I-2026-PAGE",
    sourceUrl: "https://www.upsc.gov.in/examinations/National%20Defence%20Academy%20and%20Naval%20Academy%20Examination%20%28I%29%2C%202026",
    sourceAuthority: "Union Public Service Commission",
    publishedAt: "2026-05-13",
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "WEEKLY",
    refreshTrigger: ["final result publication", "corrigendum"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Official result page could not be rechecked. The last verified written-result record is preserved.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-i-2026-final-result-status",
    pageUrl: "/nda/result",
    platform: "NDA",
    exam: "NDA & NA (I)",
    cycle: "2026",
    field: "finalResult",
    fieldLabel: "NDA I 2026 final result",
    currentValue: "Not officially published as of 12 September 2026",
    status: "NOT_ANNOUNCED",
    sourceRef: "UPSC-FINAL-RESULT-ARCHIVES",
    sourceUrl: "https://www.upsc.gov.in/exams-related-info/final-result/archives",
    sourceAuthority: "Union Public Service Commission",
    
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "WEEKLY",
    refreshTrigger: ["final result publication"],
    confidence: "HIGH",
    changePolicy: "NEVER_AUTO_PUBLISH",
    fallback: {
      publicValue: "SHOW_NOT_ANNOUNCED",
      publicMessage: "No 2026 final result exists yet. A written result is never presented as a final result.",
      actionState: "HIDE",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-ii-2026-result-status",
    pageUrl: "/nda/result",
    platform: "NDA",
    exam: "NDA & NA (II)",
    cycle: "2026",
    field: "writtenResult",
    fieldLabel: "NDA II 2026 result",
    currentValue: "Not officially published; examination scheduled 13 September 2026",
    status: "NOT_ANNOUNCED",
    sourceRef: "UPSC-NDA-II-2026-PAGE",
    sourceUrl: "https://www.upsc.gov.in/examinations/National%20Defence%20Academy%20and%20Naval%20Academy%20Examination%20%28II%29%2C%202026",
    sourceAuthority: "Union Public Service Commission",
    
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "DAILY",
    refreshTrigger: ["result notice upload"],
    confidence: "HIGH",
    changePolicy: "NEVER_AUTO_PUBLISH",
    fallback: {
      publicValue: "SHOW_NOT_ANNOUNCED",
      publicMessage: "No NDA II 2026 result exists yet. No result date is predicted.",
      actionState: "HIDE",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-i-2026-cutoff-status",
    pageUrl: "/nda/cutoff",
    platform: "NDA",
    exam: "NDA & NA (I)",
    cycle: "2026",
    field: "writtenCutoff",
    fieldLabel: "NDA I 2026 numeric cutoff",
    currentValue: "Not officially published; UPSC states marks and cutoff marks are uploaded only after the entire process and the final result",
    status: "NOT_ANNOUNCED",
    sourceRef: "UPSC-CUTOFF-INDEX",
    sourceUrl: "https://www.upsc.gov.in/examinations/cutoff-marks--",
    sourceAuthority: "Union Public Service Commission",
    
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "WEEKLY",
    refreshTrigger: ["new NDA 2026 cutoff document"],
    confidence: "HIGH",
    changePolicy: "NEVER_AUTO_PUBLISH",
    fallback: {
      publicValue: "SHOW_NOT_ANNOUNCED",
      publicMessage: "No official 2026 cutoff exists. No numeric value is inferred from any result list, trend or estimate.",
      actionState: "HIDE",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-i-2025-cutoff-historical",
    pageUrl: "/nda/cutoff",
    platform: "NDA",
    exam: "NDA & NA (I)",
    cycle: "2025",
    field: "historicalCutoff",
    fieldLabel: "NDA I 2025 official cutoff record (historical)",
    currentValue: "Written-stage minimum qualifying standard 334/900 with at least 25% in each subject; marks of the last recommended candidate at final stage 699/1800",
    status: "VERIFIED",
    sourceRef: "UPSC-CUTOFF-INDEX",
    sourceUrl: "https://www.upsc.gov.in/sites/default/files/CutOff-NDANA-I-2025-Engl-131025.pdf",
    sourceAuthority: "Union Public Service Commission",
    publishedAt: "2025-10-13",
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["document revision", "official URL change"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Historical cutoff document could not be rechecked. The last verified official values are preserved.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-ii-2026-admit-card",
    pageUrl: "/nda/admit-card",
    platform: "NDA",
    exam: "NDA & NA (II)",
    cycle: "2026",
    field: "admitCard",
    fieldLabel: "NDA II 2026 e-Admit Card",
    currentValue: "e-Admit Card uploaded 3 September 2026 for the examination on 13 September 2026; access is through the official UPSC examination page",
    status: "VERIFIED",
    sourceRef: "UPSC-NDA-II-2026-PAGE",
    sourceUrl: "https://www.upsc.gov.in/examinations/National%20Defence%20Academy%20and%20Naval%20Academy%20Examination%20%28II%29%2C%202026",
    sourceAuthority: "Union Public Service Commission",
    publishedAt: "2026-09-03",
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "DAILY",
    refreshTrigger: ["access window change", "new press note"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Official admit-card status could not be rechecked. The last verified state is preserved.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-2026-application-status",
    pageUrl: "/nda/application-form",
    platform: "NDA",
    exam: "NDA & NA (I) and (II)",
    cycle: "2026",
    field: "applicationStatus",
    fieldLabel: "NDA 2026 application windows",
    currentValue: "NDA I 2026 closed 30 December 2025 at 6:00 PM; NDA II 2026 closed 11 June 2026 at 6:00 PM; no further 2026 window is open",
    status: "VERIFIED",
    sourceRef: "UPSC-NDA-II-2026-PAGE",
    sourceUrl: "https://www.upsc.gov.in/examinations/National%20Defence%20Academy%20and%20Naval%20Academy%20Examination%20%28II%29%2C%202026",
    sourceAuthority: "Union Public Service Commission",
    publishedAt: "2026-06-11",
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "WEEKLY",
    refreshTrigger: ["new official notification", "new application window"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "Official application status could not be rechecked. The last verified closed state is preserved and no future cycle is inferred.",
      actionState: "ROUTE_TO_SOURCE_INDEX",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-2026-merit-status",
    pageUrl: "/nda/merit-list",
    platform: "NDA",
    exam: "NDA & NA (I) and (II)",
    cycle: "2026",
    field: "finalMerit",
    fieldLabel: "NDA 2026 final merit / order of merit",
    currentValue: "No 2026 final merit list is officially published as of 12 September 2026",
    status: "NOT_ANNOUNCED",
    sourceRef: "UPSC-FINAL-RESULT-ARCHIVES",
    sourceUrl: "https://www.upsc.gov.in/exams-related-info/final-result/archives",
    sourceAuthority: "Union Public Service Commission",
    
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "WEEKLY",
    refreshTrigger: ["final result publication"],
    confidence: "HIGH",
    changePolicy: "NEVER_AUTO_PUBLISH",
    fallback: {
      publicValue: "SHOW_NOT_ANNOUNCED",
      publicMessage: "No 2026 merit list exists. The NDA I 2026 written result is never relabelled as a merit list.",
      actionState: "HIDE",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
  {
    id: "nda-gat-current-affairs-scope",
    pageUrl: "/nda/gat/current-affairs",
    platform: "NDA",
    exam: "NDA & NA",
    cycle: "2026",
    field: "syllabusScope",
    fieldLabel: "Official GAT current-events scope",
    currentValue: "Recent important events in India, current important world events, and prominent Indian and international personalities, as named in the 2026 notification",
    status: "VERIFIED",
    sourceRef: "UPSC-NDA-I-2026-PAGE",
    sourceUrl: "https://www.upsc.gov.in/sites/default/files/Notif-NDA-NA-I-2026-Engl-101225.pdf",
    sourceAuthority: "Union Public Service Commission",
    publishedAt: "2025-12-10",
    lastChecked: "2026-09-12",
    lastVerified: "2026-09-12",
    refreshCadence: "MONTHLY",
    refreshTrigger: ["new notification", "syllabus revision"],
    confidence: "HIGH",
    changePolicy: "REVIEW_REQUIRED",
    fallback: {
      publicValue: "PRESERVE_LAST_VERIFIED",
      publicMessage: "The notification could not be rechecked. The last verified official scope is preserved; no news feed is generated.",
      actionState: "KEEP",
    },
    reviewRequired: true,
    reviewStatus: "APPROVED",
  },
];


/**
 * Visible "What changed" entries. Empty by design: no approved post-baseline
 * factual change has passed the review gate. Daily no-change checks, parser
 * repairs and health checks never create an entry here.
 */
export const freshnessChangeLog: FreshnessChangeLogEntry[] = [];
