import type { FreshnessSource } from "./types";

/**
 * Approved official sources for FreshnessWatch. This register is the ONLY
 * allow-list the watcher may fetch: an arbitrary URL is never monitored.
 * NEET and NDA sources are added here later with their own platform tag.
 */
export const freshnessSources: Record<string, FreshnessSource> = {
  "NTA-HOME": {
    id: "NTA-HOME",
    authority: "National Testing Agency",
    sourceUrl: "https://jeemain.nta.nic.in/",
    sourceType: "HTML_STATUS_PAGE",
    platform: "JEE",
    monitoredSignals: ["latest news", "candidate activity", "links to notices, keys and results"],
    expectedUpdateBehaviour: "Frequent changes during an active cycle",
    parserStrategy: "DOM headings and official link labels; allow-list NTA and official CDN hosts",
    fallbackStrategy: "Mark verification required; preserve last value; route user to NTA home",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "NTA-DOCS": {
    id: "NTA-DOCS",
    authority: "National Testing Agency",
    sourceUrl: "https://jeemain.nta.nic.in/documents/",
    sourceType: "HTML_INDEX",
    platform: "JEE",
    monitoredSignals: ["information bulletin", "public notices", "final answer keys", "results"],
    expectedUpdateBehaviour: "New rows and reordered rows",
    parserStrategy: "Parse row title, year and resolved URL; row order alone is never chronology",
    fallbackStrategy: "Use NTA home and public-notices index; keep last verified record",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "NTA-PUBLIC-NOTICES": {
    id: "NTA-PUBLIC-NOTICES",
    authority: "National Testing Agency",
    sourceUrl: "https://jeemain.nta.nic.in/public-notices/",
    sourceType: "HTML_INDEX",
    platform: "JEE",
    monitoredSignals: ["notice sequence", "schedule notice for the next cycle"],
    expectedUpdateBehaviour: "New notices appended during a cycle",
    parserStrategy: "Parse notice title, published date and resolved official URL",
    fallbackStrategy: "Preserve last verified value; route to NTA home",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "NTA-FINAL-KEY-S2-P1-2026": {
    id: "NTA-FINAL-KEY-S2-P1-2026",
    authority: "National Testing Agency",
    sourceUrl:
      "https://cdnbbsr.s3waas.gov.in/s3f8e59f4b2fe7c5705bf878bbd494ccdf/uploads/2026/04/20260420409057044.pdf",
    sourceType: "PDF_NOTICE",
    platform: "JEE",
    monitoredSignals: ["document availability", "revision or withdrawal", "official URL change"],
    expectedUpdateBehaviour: "Stable archival document; correction possible",
    parserStrategy: "Fingerprint the document; availability check only, never AI summarisation",
    fallbackStrategy: "Preserve last verified value; route to the official document index",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "ADV-HOME-2026": {
    id: "ADV-HOME-2026",
    authority: "JEE Advanced official organising authority",
    sourceUrl: "https://jeeadv.ac.in/",
    sourceType: "HTML_STATUS_PAGE",
    platform: "JEE",
    monitoredSignals: ["organising authority", "dates", "papers", "answer keys", "results"],
    expectedUpdateBehaviour: "Announcements added through the cycle",
    parserStrategy: "Parse announcement headings, timestamps and official links",
    fallbackStrategy: "Preserve last value; route to homepage; review any conflict",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "ADV-DATES-2026": {
    id: "ADV-DATES-2026",
    authority: "JEE Advanced official organising authority",
    sourceUrl: "https://jeeadv.ac.in/imp_dates.html",
    sourceType: "HTML_INDEX",
    platform: "JEE",
    monitoredSignals: ["registration", "admit card", "exam", "answer keys", "result"],
    expectedUpdateBehaviour: "Stable, but may be superseded by a notice",
    parserStrategy: "Parse activity, date, time and 'Last Updated'; compare with announcements",
    fallbackStrategy: "Prefer a reviewed superseding notice; never resolve a conflict automatically",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "ADV-CUTOFF-2026": {
    id: "ADV-CUTOFF-2026",
    authority: "JEE Advanced 2026 organising authority",
    sourceUrl: "https://jeeadv.ac.in/documents/cutoffs_2026.pdf",
    sourceType: "PDF_DATA_TABLE",
    platform: "JEE",
    monitoredSignals: ["qualifying marks table", "replacement PDF"],
    expectedUpdateBehaviour: "Archival for the cycle; correction possible",
    parserStrategy: "Labelled table extraction after table QA; unparsable change becomes REVIEW_REQUIRED",
    fallbackStrategy: "Preserve last verified table; keep the official source link",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  JOSAA: {
    id: "JOSAA",
    authority: "Joint Seat Allocation Authority",
    sourceUrl: "https://josaa.nic.in/",
    sourceType: "INTERACTIVE_PORTAL",
    platform: "JEE",
    monitoredSignals: ["counselling schedule", "opening and closing rank archives"],
    expectedUpdateBehaviour: "Portal opens per counselling cycle",
    parserStrategy: "Portal availability and labelled archive entries only; no derived ranks",
    fallbackStrategy: "Route to the portal; never publish an unreviewed rank value",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  CSAB: {
    id: "CSAB",
    authority: "Central Seat Allocation Board",
    sourceUrl: "https://csab.nic.in/",
    sourceType: "INTERACTIVE_PORTAL",
    platform: "JEE",
    monitoredSignals: ["special round schedule", "closing rank archives"],
    expectedUpdateBehaviour: "Opens after the JoSAA rounds close",
    parserStrategy: "Portal availability and labelled archive entries only",
    fallbackStrategy: "Route to the portal; preserve last verified statement",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "INTERNAL-DATASET-REGISTER": {
    id: "INTERNAL-DATASET-REGISTER",
    authority: "Rank Sarthi editorial control",
    sourceUrl: "https://ranksarthi.com/jee/analysis",
    sourceType: "HTML_STATUS_PAGE",
    platform: "JEE",
    monitoredSignals: ["approved analysed dataset created, corrected or withdrawn"],
    expectedUpdateBehaviour: "Changes only through editorial sign-off",
    parserStrategy: "Internal register lookup; never an external fetch",
    fallbackStrategy: "Analysis remains unavailable until a reviewed dataset exists",
    trustTier: "PRIMARY_OWNER",
    enabled: false,
  },

  /* NEET R01 allow-list (National Testing Agency) */
  "NEET-HOME": {
    id: "NEET-HOME",
    authority: "National Testing Agency",
    sourceUrl: "https://neet.nta.nic.in/",
    sourceType: "HTML_STATUS_PAGE",
    platform: "NEET",
    monitoredSignals: ["latest notices", "answer key links", "result links", "schedule notices"],
    expectedUpdateBehaviour: "Frequent changes during an active cycle",
    parserStrategy: "DOM headings and official link labels; allow-list NTA and official CDN hosts",
    fallbackStrategy: "Preserve last verified value; route the user to the official NEET homepage",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "NEET-ARCHIVE": {
    id: "NEET-ARCHIVE",
    authority: "National Testing Agency",
    sourceUrl: "https://neet.nta.nic.in/archive/",
    sourceType: "HTML_INDEX",
    platform: "NEET",
    monitoredSignals: ["question-paper files by code and language", "historical answer keys"],
    expectedUpdateBehaviour: "New archive rows after a cycle closes",
    parserStrategy: "Parse row title, cycle and resolved official file URL",
    fallbackStrategy: "Keep SOURCE_PENDING when an exact official file is unavailable",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "NTA-NOTICE-ARCHIVE": {
    id: "NTA-NOTICE-ARCHIVE",
    authority: "National Testing Agency",
    sourceUrl: "https://www.nta.ac.in/NoticeBoardArchive",
    sourceType: "HTML_INDEX",
    platform: "NEET",
    monitoredSignals: ["archived NEET notices", "historical key notices"],
    expectedUpdateBehaviour: "Append-only archive index",
    parserStrategy: "Parse notice title, date and resolved official document URL",
    fallbackStrategy: "Official index only; never activate a CTA without an exact file",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "NEET-2026-REEXAM-FINAL-KEY": {
    id: "NEET-2026-REEXAM-FINAL-KEY",
    authority: "National Testing Agency",
    sourceUrl:
      "https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/07/20260716131467523.pdf",
    sourceType: "PDF_NOTICE",
    platform: "NEET",
    monitoredSignals: ["final answer key document for the 21 Jun 2026 re-examination"],
    expectedUpdateBehaviour: "Immutable once published; replaced only by a further official notice",
    parserStrategy: "Verify document identity, exam event and publication date",
    fallbackStrategy: "Preserve last verified key; never substitute a coaching key",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "NEET-KEY-DATA-POINTS": {
    id: "NEET-KEY-DATA-POINTS",
    authority: "National Testing Agency",
    sourceUrl:
      "https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/07/202607161539405935.pdf",
    sourceType: "PDF_DATA_TABLE",
    platform: "NEET",
    monitoredSignals: [
      "category-wise qualifying percentile",
      "official marks range",
      "qualified candidates",
    ],
    expectedUpdateBehaviour: "Replaced by a newer official key-data document after a result",
    parserStrategy: "Compare cycleYear + category + qualifying percentile + marks range",
    fallbackStrategy: "Preserve the prior verified cycle; never publish admission closing ranks here",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "NEET-2026-RESULT-NOTICE": {
    id: "NEET-2026-RESULT-NOTICE",
    authority: "National Testing Agency",
    sourceUrl:
      "https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/07/20260716477215762.pdf",
    sourceType: "PDF_NOTICE",
    platform: "NEET",
    monitoredSignals: ["result declaration date", "recorded-response window", "final key date"],
    expectedUpdateBehaviour: "Immutable press release for the 2026 cycle",
    parserStrategy: "Compare event identity, milestone type and official date range",
    fallbackStrategy: "Preserve last verified milestone values",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  /* JEE J01 allow-list additions */
  "NTA-FINAL-KEY-S1-P1-2026": {
    id: "NTA-FINAL-KEY-S1-P1-2026",
    authority: "National Testing Agency",
    sourceUrl:
      "https://cdnbbsr.s3waas.gov.in/s3f8e59f4b2fe7c5705bf878bbd494ccdf/uploads/2026/02/20260216459398513.pdf",
    sourceType: "PDF_NOTICE",
    platform: "JEE",
    monitoredSignals: ["document availability", "revision or withdrawal", "official URL change"],
    expectedUpdateBehaviour: "Stable archival document; correction possible",
    parserStrategy: "Fingerprint the document; availability check only, never AI summarisation",
    fallbackStrategy: "Preserve last verified value; route to the official document index",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "NTA-RESULT-NOTICE-2026": {
    id: "NTA-RESULT-NOTICE-2026",
    authority: "National Testing Agency",
    sourceUrl: "https://www.nta.ac.in/Download/Notice/Notice_20260420194021.pdf",
    sourceType: "PDF_DATA_TABLE",
    platform: "JEE",
    monitoredSignals: ["category-wise NTA Score threshold", "candidate counts", "corrected notice"],
    expectedUpdateBehaviour: "Archival for the cycle; correction possible",
    parserStrategy: "Labelled table extraction after table QA; unparsable change becomes REVIEW_REQUIRED",
    fallbackStrategy: "Preserve last verified table; keep the official source link",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "ADV-ARCHIVE": {
    id: "ADV-ARCHIVE",
    authority: "JEE Advanced official organising authority",
    sourceUrl: "https://jeeadv.ac.in/archive.html",
    sourceType: "HTML_INDEX",
    platform: "JEE",
    monitoredSignals: ["past question-paper rows by year, paper and language"],
    expectedUpdateBehaviour: "New rows after a cycle closes",
    parserStrategy: "Parse row year, paper number, language and resolved official file URL",
    fallbackStrategy: "Keep the last verified rows; leave an unverified file inactive",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },

  /* ---------------- NDA (UPSC) ---------------- */
  "UPSC-NDA-I-2026-PAGE": {
    id: "UPSC-NDA-I-2026-PAGE",
    authority: "Union Public Service Commission",
    sourceUrl:
      "https://www.upsc.gov.in/examinations/National%20Defence%20Academy%20and%20Naval%20Academy%20Examination%20%28I%29%2C%202026",
    sourceType: "HTML_STATUS_PAGE",
    platform: "NDA",
    monitoredSignals: ["milestone rows", "question-paper uploads", "written and final result notices"],
    expectedUpdateBehaviour: "New document rows appended as the cycle progresses",
    parserStrategy: "Parse document type, label and resolved upsc.gov.in URL; keep NDA-I event identity",
    fallbackStrategy: "Preserve last verified value; route to the official examination page",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "UPSC-NDA-II-2026-PAGE": {
    id: "UPSC-NDA-II-2026-PAGE",
    authority: "Union Public Service Commission",
    sourceUrl:
      "https://www.upsc.gov.in/examinations/National%20Defence%20Academy%20and%20Naval%20Academy%20Examination%20%28II%29%2C%202026",
    sourceType: "HTML_STATUS_PAGE",
    platform: "NDA",
    monitoredSignals: ["e-Admit Card state", "time table", "press notes", "question papers", "result notices"],
    expectedUpdateBehaviour: "Active cycle: rows appended around exam and result windows",
    parserStrategy: "Parse document type, label and resolved upsc.gov.in URL; keep NDA-II event identity",
    fallbackStrategy: "Preserve last verified value; route to the official examination page",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "UPSC-PREVIOUS-PAPERS": {
    id: "UPSC-PREVIOUS-PAPERS",
    authority: "Union Public Service Commission",
    sourceUrl: "https://www.upsc.gov.in/examinations/previous-question-papers",
    sourceType: "HTML_INDEX",
    platform: "NDA",
    monitoredSignals: ["new question-paper rows by examination and year"],
    expectedUpdateBehaviour: "New rows appended after an examination cycle",
    parserStrategy: "Match examination name, year and paper; never guess a URL pattern",
    fallbackStrategy: "Keep pending rows inactive; no substitute copy is shown",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "UPSC-ANSWER-KEY-INDEX": {
    id: "UPSC-ANSWER-KEY-INDEX",
    authority: "Union Public Service Commission",
    sourceUrl: "https://www.upsc.gov.in/examinations/answer-key",
    sourceType: "HTML_INDEX",
    platform: "NDA",
    monitoredSignals: ["answer-key rows by examination and year"],
    expectedUpdateBehaviour: "Keys appear only after the full official process",
    parserStrategy: "Match examination name and year exactly; a coaching key is never accepted",
    fallbackStrategy: "Keep answer-key actions disabled",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "UPSC-CUTOFF-INDEX": {
    id: "UPSC-CUTOFF-INDEX",
    authority: "Union Public Service Commission",
    sourceUrl: "https://www.upsc.gov.in/examinations/cutoff-marks--",
    sourceType: "HTML_INDEX",
    platform: "NDA",
    monitoredSignals: ["new cut-off documents by examination and year"],
    expectedUpdateBehaviour: "Published only after the final result of a cycle",
    parserStrategy: "Match examination and year; numeric values are never inferred",
    fallbackStrategy: "Show the official not-yet-published state",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
  "UPSC-FINAL-RESULT-ARCHIVES": {
    id: "UPSC-FINAL-RESULT-ARCHIVES",
    authority: "Union Public Service Commission",
    sourceUrl: "https://www.upsc.gov.in/exams-related-info/final-result/archives",
    sourceType: "HTML_INDEX",
    platform: "NDA",
    monitoredSignals: ["final result / order-of-merit documents"],
    expectedUpdateBehaviour: "New final results appended per cycle",
    parserStrategy: "Match examination and cycle; written results are never read as merit lists",
    fallbackStrategy: "Preserve the current status statement",
    trustTier: "PRIMARY_OWNER",
    enabled: true,
  },
};


export function getFreshnessSource(id: string): FreshnessSource | undefined {
  return freshnessSources[id];
}

/** The watcher may only fetch a URL that belongs to an enabled approved source. */
export function isApprovedSourceUrl(url: string): boolean {
  return Object.values(freshnessSources).some((s) => s.enabled && s.sourceUrl === url);
}
