/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlatformIndexRouteImport } from './routes/$platform.index'
import { Route as PlatformSyllabusRouteImport } from './routes/$platform.syllabus'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as PlatformSubjectIndexRouteImport } from './routes/$platform.$subject.index'
import { Route as PlatformSubjectChapterRouteImport } from './routes/$platform.$subject.$chapter'
import { Route as ApiPublicBlogArticleRouteImport } from './routes/api/public/blog-article'
import { Route as ApiPublicBlogCommentsRouteImport } from './routes/api/public/blog-comments'
import { Route as ApiPublicBlogListRouteImport } from './routes/api/public/blog-list'
import { Route as ApiPublicFreshnessRefreshRouteImport } from './routes/api/public/freshness-refresh'
import { Route as PlatformSubjectChapterTopicRouteImport } from './routes/$platform.$subject.$chapter_.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/$platform/',
  path: '/$platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSyllabusRoute = PlatformSyllabusRouteImport.update({
  id: '/$platform/syllabus',
  path: '/$platform/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSubjectIndexRoute = PlatformSubjectIndexRouteImport.update({
  id: '/$platform/$subject/',
  path: '/$platform/$subject/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSubjectChapterRoute = PlatformSubjectChapterRouteImport.update({
  id: '/$platform/$subject/$chapter',
  path: '/$platform/$subject/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBlogArticleRoute = ApiPublicBlogArticleRouteImport.update({
  id: '/api/public/blog-article',
  path: '/api/public/blog-article',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBlogCommentsRoute = ApiPublicBlogCommentsRouteImport.update({
  id: '/api/public/blog-comments',
  path: '/api/public/blog-comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBlogListRoute = ApiPublicBlogListRouteImport.update({
  id: '/api/public/blog-list',
  path: '/api/public/blog-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFreshnessRefreshRoute =
  ApiPublicFreshnessRefreshRouteImport.update({
    id: '/api/public/freshness-refresh',
    path: '/api/public/freshness-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformSubjectChapterTopicRoute =
  PlatformSubjectChapterTopicRouteImport.update({
    id: '/$platform/$subject/$chapter_/$topic',
    path: '/$platform/$subject/$chapter/$topic',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$platform/syllabus': typeof PlatformSyllabusRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$platform/': typeof PlatformIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$platform/$subject/$chapter': typeof PlatformSubjectChapterRoute
  '/api/public/blog-article': typeof ApiPublicBlogArticleRoute
  '/api/public/blog-comments': typeof ApiPublicBlogCommentsRoute
  '/api/public/blog-list': typeof ApiPublicBlogListRoute
  '/api/public/freshness-refresh': typeof ApiPublicFreshnessRefreshRoute
  '/$platform/$subject/': typeof PlatformSubjectIndexRoute
  '/$platform/$subject/$chapter/$topic': typeof PlatformSubjectChapterTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$platform/syllabus': typeof PlatformSyllabusRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$platform': typeof PlatformIndexRoute
  '/blog': typeof BlogIndexRoute
  '/$platform/$subject/$chapter': typeof PlatformSubjectChapterRoute
  '/api/public/blog-article': typeof ApiPublicBlogArticleRoute
  '/api/public/blog-comments': typeof ApiPublicBlogCommentsRoute
  '/api/public/blog-list': typeof ApiPublicBlogListRoute
  '/api/public/freshness-refresh': typeof ApiPublicFreshnessRefreshRoute
  '/$platform/$subject': typeof PlatformSubjectIndexRoute
  '/$platform/$subject/$chapter/$topic': typeof PlatformSubjectChapterTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$platform/syllabus': typeof PlatformSyllabusRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$platform/': typeof PlatformIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$platform/$subject/$chapter': typeof PlatformSubjectChapterRoute
  '/api/public/blog-article': typeof ApiPublicBlogArticleRoute
  '/api/public/blog-comments': typeof ApiPublicBlogCommentsRoute
  '/api/public/blog-list': typeof ApiPublicBlogListRoute
  '/api/public/freshness-refresh': typeof ApiPublicFreshnessRefreshRoute
  '/$platform/$subject/': typeof PlatformSubjectIndexRoute
  '/$platform/$subject/$chapter_/$topic': typeof PlatformSubjectChapterTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostic'
    | '/sitemap'
    | '/sitemap.xml'
    | '/$platform/syllabus'
    | '/blog/$slug'
    | '/$platform/'
    | '/blog/'
    | '/$platform/$subject/$chapter'
    | '/api/public/blog-article'
    | '/api/public/blog-comments'
    | '/api/public/blog-list'
    | '/api/public/freshness-refresh'
    | '/$platform/$subject/'
    | '/$platform/$subject/$chapter/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostic'
    | '/sitemap'
    | '/sitemap.xml'
    | '/$platform/syllabus'
    | '/blog/$slug'
    | '/$platform'
    | '/blog'
    | '/$platform/$subject/$chapter'
    | '/api/public/blog-article'
    | '/api/public/blog-comments'
    | '/api/public/blog-list'
    | '/api/public/freshness-refresh'
    | '/$platform/$subject'
    | '/$platform/$subject/$chapter/$topic'
  id:
    | '__root__'
    | '/'
    | '/diagnostic'
    | '/sitemap'
    | '/sitemap.xml'
    | '/$platform/syllabus'
    | '/blog/$slug'
    | '/$platform/'
    | '/blog/'
    | '/$platform/$subject/$chapter'
    | '/api/public/blog-article'
    | '/api/public/blog-comments'
    | '/api/public/blog-list'
    | '/api/public/freshness-refresh'
    | '/$platform/$subject/'
    | '/$platform/$subject/$chapter_/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticRoute: typeof DiagnosticRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PlatformSyllabusRoute: typeof PlatformSyllabusRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PlatformSubjectChapterRoute: typeof PlatformSubjectChapterRoute
  ApiPublicBlogArticleRoute: typeof ApiPublicBlogArticleRoute
  ApiPublicBlogCommentsRoute: typeof ApiPublicBlogCommentsRoute
  ApiPublicBlogListRoute: typeof ApiPublicBlogListRoute
  ApiPublicFreshnessRefreshRoute: typeof ApiPublicFreshnessRefreshRoute
  PlatformSubjectIndexRoute: typeof PlatformSubjectIndexRoute
  PlatformSubjectChapterTopicRoute: typeof PlatformSubjectChapterTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$platform/': {
      id: '/$platform/'
      path: '/$platform'
      fullPath: '/$platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$platform/syllabus': {
      id: '/$platform/syllabus'
      path: '/$platform/syllabus'
      fullPath: '/$platform/syllabus'
      preLoaderRoute: typeof PlatformSyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$platform/$subject/': {
      id: '/$platform/$subject/'
      path: '/$platform/$subject'
      fullPath: '/$platform/$subject/'
      preLoaderRoute: typeof PlatformSubjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$platform/$subject/$chapter': {
      id: '/$platform/$subject/$chapter'
      path: '/$platform/$subject/$chapter'
      fullPath: '/$platform/$subject/$chapter'
      preLoaderRoute: typeof PlatformSubjectChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blog-article': {
      id: '/api/public/blog-article'
      path: '/api/public/blog-article'
      fullPath: '/api/public/blog-article'
      preLoaderRoute: typeof ApiPublicBlogArticleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blog-comments': {
      id: '/api/public/blog-comments'
      path: '/api/public/blog-comments'
      fullPath: '/api/public/blog-comments'
      preLoaderRoute: typeof ApiPublicBlogCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blog-list': {
      id: '/api/public/blog-list'
      path: '/api/public/blog-list'
      fullPath: '/api/public/blog-list'
      preLoaderRoute: typeof ApiPublicBlogListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/freshness-refresh': {
      id: '/api/public/freshness-refresh'
      path: '/api/public/freshness-refresh'
      fullPath: '/api/public/freshness-refresh'
      preLoaderRoute: typeof ApiPublicFreshnessRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$platform/$subject/$chapter_/$topic': {
      id: '/$platform/$subject/$chapter_/$topic'
      path: '/$platform/$subject/$chapter/$topic'
      fullPath: '/$platform/$subject/$chapter/$topic'
      preLoaderRoute: typeof PlatformSubjectChapterTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticRoute: DiagnosticRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PlatformSyllabusRoute: PlatformSyllabusRoute,
  BlogSlugRoute: BlogSlugRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  PlatformSubjectChapterRoute: PlatformSubjectChapterRoute,
  ApiPublicBlogArticleRoute: ApiPublicBlogArticleRoute,
  ApiPublicBlogCommentsRoute: ApiPublicBlogCommentsRoute,
  ApiPublicBlogListRoute: ApiPublicBlogListRoute,
  ApiPublicFreshnessRefreshRoute: ApiPublicFreshnessRefreshRoute,
  PlatformSubjectIndexRoute: PlatformSubjectIndexRoute,
  PlatformSubjectChapterTopicRoute: PlatformSubjectChapterTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
